import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/header/Header";
import ReactQueryProviders from "@/hook/useReactQuery";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const myFont = localFont({
  src: [
    {
      path: "/fonts/GmarketSansTTFLight.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "/fonts/GmarketSansTTFMedium.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/GmarketSansTTFBold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  display: "block",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={myFont.className}>
        <ReactQueryProviders>
          <Header />
          <main>{children}</main>
          <Footer />
        </ReactQueryProviders>
      </body>
    </html>
  );
}
